name: Build FROS Firmware

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y cmake curl wget vim git antlr3 asciidoc autoconf automake autopoint binutils bison \
          build-essential bzip2 ccache cpio device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib \
          gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev \
          libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz \
          mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools \
          libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip \
          xmlto xxd zlib1g-dev ack

      - name: Clone FROS source code
        run: |
          git clone https://github.com/yangtom401/fros.git
          cd fros
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Build Firmware
        run: |
          cd fros
          ./build.sh -l x86_64  

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: 'v1.0.0' # 你可以根据需要更改版本号
          release_name: 'FROS Firmware Release'
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Firmware to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: fros/bin/psg1208-firmware.bin # 请根据实际生成的固件路径修改
          asset_name: 'psg1208-firmware.bin'
          asset_content_type: 'application/octet-stream'
